### ISSUE TITLE
hot reload does not seem to work

### ISSUE THREAD

**Issue by amitport** [shellscape/koa-webpack#29]
(or even basic live-reload)

possibly related issues:
https://github.com/shellscape/koa-webpack/issues/25
https://github.com/shellscape/koa-webpack/issues/11
https://github.com/shellscape/koa-webpack/issues/20

**Comment by shellscape** [comment]
thanks for the interest in the project. unfortunately your issue has no substance. linking to other issues doesn't make a new issue I'm afraid. if you'd like to provide your code for others to help you work through the problem - after you've described the issue, and the steps you've taken to triage or discover any causes of the issue - please do. otherwise, if you'd like to contribute to the other issues that you feel are related, please do. it sounds like that's the best route for you to take.

given the reasons I've listed, I'm closing this issue.

**Comment by cmoad** [comment]
Created #30 that has a tangible example of this.

**Comment by amitport** [comment]
@shellscape 
Myself and others who posted related issues are telling you that either it doesn't work in general or that there is not enough documentation to understand why it doesn't work or how to even create a valid setup.

You may consider this a documentation issue, or decide to leave things unmaintained as they are, but it is a very real issue that makes your library unusable to the point that we can't event provide a focused issue (linking to other issue those not create a new issue, but it does confirms that there is one)

**Comment by shellscape** [comment]
@amitport I'm sorry but that's utter nonsense. You might consider reading over this classic piece: http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

The documentation available is aplenty for both [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware#installation--usage) and [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware/#usage) and the [README](https://github.com/shellscape/koa-webpack#dev) for this module clearly states that it's composing those two modules and providing a means to both pass config to them, and manipulate them directly. If you feel that documentation is lacking, then _suggest amendments to the documentation in the form of a pull request_ rather than simply complaining about it.

This module is neither unmaintained, as evidenced by the commit log and contributions of others, nor is it unusable. To suggest either further discredits a poorly written and barren issue.
