### ISSUE TITLE
Can't get to work 

### ISSUE THREAD

**Issue by SPAHI4** [shellscape/koa-webpack#33]
```
    "koa-webpack": "^0.3.1",
    "react-hot-loader": "next",
    "webpack-dev-server": "^2.4.1"
```

```
	entry: [
		'react-hot-loader/patch',
		// activate HMR for React

		'webpack-dev-server/client?/__webpack_hmr',
		// bundle the client for webpack-dev-server
		// and connect to the provided endpoint

		'webpack/hot/only-dev-server',
		// bundle the client for hot reloading
		// only- means to only hot reload for successful updates

		'./client/index.js',
	],
```

```
const middleware = koaWebpack({
	compiler
});

app.use(middleware);
```

Error:
```
abstract-xhr.js:132 GET http://localhost:1488/__webpack_hmr/info?t=1489273162796 404 (Not Found)
```

**Comment by shellscape** [comment]
This isn't an issue but rather a call for support. There are also a bunch of other issues addressing the same 404. This is a configuration issue on your end, rather than a bug in module. The documentation for both webpack-dev-middleware and webpack-hot-middleware are available on their respective repos. Please give those a read and check out the other closed issues tackling the 404 error.

**Comment by SPAHI4** [comment]
Seems like it's an issue with webpack-dev-middleware https://github.com/webpack/webpack-dev-middleware/issues/174
