### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by pearofducks** [shellscape/koa-webpack#94]
The [hotClient](https://github.com/shellscape/koa-webpack#hotclient) section still refers to the property name as `hot` in the paragraph.

e.g.

> The `hot` property ... 

(Sorry for not PR'ing this, short on time right now!)

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.

**Comment by shellscape** [comment]
@Lavoaster it's not pedantic if users flat out ignore issue templates. my account is setup to automatically reply with that message, tag, and close an issue for which the user removed the issue template. Templates have been around long enough on Github and this is fairly common practice anymore. Next time you spot something you'd like to discuss, please reach out using another channel rather than using an issue reply.
